/* This file is generated by scripts/build-site-data.mjs. Do not edit manually. */

export const generatedCategoryOrder = [
  "personal",
  "film",
  "portrait"
] as const;

export const generatedCategoryLabels = {
  "personal": "personal",
  "film": "film",
  "portrait": "portrait"
} as const;

export const generatedSiteData = {
  "site": {
    "name": "Michael Yuan",
    "shortName": "Michael Yuan",
    "tagline": "Photography",
    "instagramUrl": "https://instagram.com/ilikecalculus",
    "blogUrl": "https://ilikecalculus.substack.com/"
  },
  "about": {
    "title": "About",
    "paragraphs": [
      "Hey there! I’m Michael Yuan.",
      "I split my time between building software and making art. By day, I’m a software engineer at Figma, working on tools that help teams design and build together."
    ],
    "image": {
      "src": "/media/about/about-20240831-dscf6193.jpg",
      "width": 4365,
      "height": 5456,
      "alt": "About portrait"
    }
  },
  "contact": {
    "title": "Contact",
    "paragraphs": [
      "I’m a visual artist working in the medium of photography, motivated by reframing the familiar. I’m drawn to the overlooked surfaces and objects of the world we build—and the marks they accumulate. Through perspective play, I shrink, flatten, and contort the everyday to draw out the subtle presence of humanity as residue: wear, repair, intention, neglect. I search for quiet solitude—and for the memories of places, things, and people that have become more invisible as time and culture shift.",
      "Looking to collaborate, share an idea, or ask a question? Send me a message—I’d love to hear from you. If you’re curious, I’ll also tell you the origin story behind ilikecalculus."
    ],
    "image": {
      "src": "/media/contact/banner.jpg",
      "width": 2500,
      "height": 833,
      "alt": "Contact portrait"
    }
  },
  "press": [
    {
      "outlet": "Leica Blog",
      "title": "Michael Yuan: The Bridge",
      "url": "https://lfi-online.de/ceemes/en/blog/michael-yuan-the-bridge-2693.html"
    },
    {
      "outlet": "SFGate",
      "title": "See the Golden Gate Bridge like you never have before",
      "url": "https://www.sfgate.com/living/article/Golden-Gate-Bridge-photographer-Michael-Yuan-15668793.php"
    },
    {
      "outlet": "PetaPixel",
      "title": "The Bridge, Reconstructed: A Different Perspective of the Golden Gate Bridge",
      "url": "https://petapixel.com/2020/10/05/the-bridge-reconstructed-a-different-perspective-of-the-golden-gate-bridge/"
    },
    {
      "outlet": "LifeFramer",
      "title": "Reimagining an Icon",
      "url": "https://www.life-framer.com/michael-yuan/"
    },
    {
      "outlet": "Artwort",
      "title": "The Bridge, Reconstructed – Il Golden Gate Bridge da ricostruire nelle fotografie di Michael Yuan",
      "url": "https://www.artwort.com/2020/11/03/fotografia/the-bridge-reconstructed-michael-yuan/"
    },
    {
      "outlet": "Plain Magazine",
      "title": "The Golden Gate Bridge, Deconstructed and Delightfully Unrecognizable",
      "url": "https://plainmagazine.com/michael-yuan-golden-gate-bridge/"
    },
    {
      "outlet": "Architectural Photography Almanac",
      "title": "Math Aficionado Michael Yuan Hones in on the Golden Ratios of the Golden Gate Bridge",
      "url": "https://apalmanac.com/potw/math-aficionado-michael-yuan-hones-in-on-the-golden-ratios-of-the-golden-gate-bridge-13773"
    },
    {
      "outlet": "Dodho Magazine",
      "title": "Golden Gate; The Bridge, Reconstructed by Michael Yuan",
      "url": "https://www.dodho.com/golden-gate-the-bridge-reconstructed-by-michael-yuan/"
    },
    {
      "outlet": "The Photo Argus",
      "title": "Incredible Pictures of Basketball Courts – “Urban Courts” by Michael Yuan",
      "url": "https://www.thephotoargus.com/incredible-pictures-of-basketball-courts-urban-courts-by-michael-yuan/"
    },
    {
      "outlet": "Le Blog de Fabien Ribery",
      "title": "The Bridge, l’âme du métal, par Michael Yuan, ingénieur photographe",
      "url": "https://lintervalle.blog/2022/08/03/the-bridge-lame-du-metal-par-michael-yuan-ingenieur-photographe/"
    },
    {
      "outlet": "Glasstire",
      "title": "A Shockingly Modernist Project and Others: Four Books of Photographs",
      "url": "https://glasstire.com/2023/01/04/a-shockingly-modernist-project-and-others-four-books-of-photographs/"
    }
  ],
  "where": {
    "locations": [
      {
        "id": "dc8310fa-5d26-4ec7-8380-4cb104de57db",
        "label": "New York City",
        "latitude": 40.718117449032434,
        "longitude": -73.95747908497457,
        "at": "2026-01-02T17:00:00.000Z",
        "note": "Finally in NYC after a month of traveling"
      },
      {
        "id": "ecf5e8ba-d4da-4705-b6d5-5fffb50b8f22",
        "label": "Hong Kong",
        "latitude": 22.28117547134755,
        "longitude": 114.18595157291284,
        "at": "2026-02-28T00:45:00.000Z",
        "note": "Starting my sabbatical in Hong Kong"
      },
      {
        "id": "43dce09f-7884-4629-9dec-c4db9fb26251",
        "label": "Taipei",
        "latitude": 25.03346844531645,
        "longitude": 121.56495420459811,
        "at": "2025-12-30T13:50:00.000Z",
        "note": "NYE countdown in Taipei with DQ"
      },
      {
        "id": "3562c808-96dd-4ebf-96ea-b76e7a5cf38c",
        "label": "Kanazawa",
        "latitude": 36.57864660027996,
        "longitude": 136.64766678471085,
        "at": "2026-03-04T11:30:00.000Z",
        "note": "Flew into Tokyo and trained straight to Kanazawa. This is the start of the road trip!"
      },
      {
        "id": "96735476-b446-423e-9bb3-5c1ba4dc8a5d",
        "label": "Taitung",
        "latitude": 22.755421688207196,
        "longitude": 121.1485379073298,
        "at": "2025-12-24T11:30:00.000Z",
        "note": "Spending Christmas with DQ"
      },
      {
        "id": "eb43a1c1-bd23-44af-95dc-b0a5e7fab99f",
        "label": "Taipei",
        "latitude": 25.03346844531645,
        "longitude": 121.56495420459811,
        "at": "2025-12-23T08:15:00.000Z",
        "note": "Taipei layover for Taitung"
      },
      {
        "id": "0a7321fb-21d3-4b4d-9005-4358fe5b3555",
        "label": "Tokyo",
        "latitude": 35.68906097726562,
        "longitude": 139.71508499653592,
        "at": "2025-12-01T14:30:00.000Z",
        "note": "Working remotely in Tokyo for a month"
      },
      {
        "id": "df073ae0-2e02-4e23-9a3b-a49a72ce31b0",
        "label": "San Francisco",
        "latitude": 37.62193970897527,
        "longitude": -122.38251453291625,
        "at": "2025-11-26T12:00:00.000Z",
        "note": "Friendsgiving"
      },
      {
        "id": "83d22273-651b-4267-887f-9bfbac33a8aa",
        "label": "Ine",
        "latitude": 35.67573145950988,
        "longitude": 135.2868706731373,
        "at": "2026-03-07T04:00:00.000Z",
        "note": "Staying overnight at a quaint fishing village"
      },
      {
        "id": "bf17b376-b072-4af6-9484-bf80345dc59f",
        "label": "Tottori",
        "latitude": 35.41206474296221,
        "longitude": 133.89358911549002,
        "at": "2026-03-08T09:00:00.000Z",
        "note": "Staying at a hot spring hotel with a beautiful garden (Izanro Iwasaki)."
      }
    ]
  },
  "projects": [
    {
      "slug": "the-bridge-reconstructed",
      "categories": [
        "personal"
      ],
      "title": "The Bridge",
      "description": "A new perspective on an iconic subject.",
      "coverImage": {
        "src": "/media/projects/the-bridge-reconstructed/01.jpg",
        "width": 2500,
        "height": 3750,
        "alt": "The Bridge"
      },
      "images": [
        {
          "src": "/media/projects/the-bridge-reconstructed/01.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20180217-DSCF1489.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/02.jpg",
          "width": 2500,
          "height": 3749,
          "alt": "20190210-DSCF7837-Edit.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/03.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "20190901-DSCF4044.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/04.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20190901-DSCF3823.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/06.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20190210-DSCF8005-Edit.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/16.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20190210-DSCF7769.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/05.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20200501-DSCF1365.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/15.jpg",
          "width": 2500,
          "height": 1250,
          "alt": "20191005-DSCF4665.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/14.jpg",
          "width": 2000,
          "height": 4000,
          "alt": "20191005-DSCF4669.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/27.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20190210-DSCF7872.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/23.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20190210-DSCF7719-Edit.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/11.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20200617-DSCF1967.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/10.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20191005-DSCF4685.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/20.jpg",
          "width": 2000,
          "height": 3000,
          "alt": "20200704-DSCF2203.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/21.jpg",
          "width": 2000,
          "height": 3000,
          "alt": "20200704-DSCF2215.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/12.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "20200501-DSCF1379.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/13.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20200501-DSCF1370.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/17.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20190210-DSCF7957.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/19.jpg",
          "width": 2500,
          "height": 1786,
          "alt": "20191005-DSCF4632.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/18.jpg",
          "width": 2500,
          "height": 1786,
          "alt": "20200119-DSCF8049.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/07.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20191005-DSCF4589.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/08.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20191005-DSCF4605.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/09.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20190513-DSCF1492.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/22.jpg",
          "width": 2500,
          "height": 3749,
          "alt": "20200704-DSCF2235.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/24.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20190210-DSCF7732.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/25.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20190210-DSCF7737.jpg"
        },
        {
          "src": "/media/projects/the-bridge-reconstructed/26.jpg",
          "width": 2000,
          "height": 2800,
          "alt": "20200704-DSCF2241.jpg"
        }
      ]
    },
    {
      "slug": "urban-courts",
      "categories": [
        "personal"
      ],
      "title": "Urban Courts",
      "description": "Basketball courts across the world.",
      "coverImage": {
        "src": "/media/projects/urban-courts/01.jpg",
        "width": 2500,
        "height": 3750,
        "alt": "Urban Courts"
      },
      "images": [
        {
          "src": "/media/projects/urban-courts/03.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "20181013-DSCF3350.jpg"
        },
        {
          "src": "/media/projects/urban-courts/02.jpg",
          "width": 2250,
          "height": 4000,
          "alt": "20181012-DSCF2991.jpg"
        },
        {
          "src": "/media/projects/urban-courts/17.jpg",
          "width": 2143,
          "height": 3000,
          "alt": "20210809-DSCF5285.jpg"
        },
        {
          "src": "/media/projects/urban-courts/13.jpg",
          "width": 2500,
          "height": 2000,
          "alt": "20200628-DSCF2055.jpg"
        },
        {
          "src": "/media/projects/urban-courts/14.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20190331-DSCF0428.jpg"
        },
        {
          "src": "/media/projects/urban-courts/06.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20191103-DSCF6332.jpg"
        },
        {
          "src": "/media/projects/urban-courts/18.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "20210809-DSCF5287.jpg"
        },
        {
          "src": "/media/projects/urban-courts/31.jpg",
          "width": 2500,
          "height": 3333,
          "alt": "20220820-DSCF0126.jpg"
        },
        {
          "src": "/media/projects/urban-courts/30.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230403-DSCF1566 2.jpg"
        },
        {
          "src": "/media/projects/urban-courts/01.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20180913-DSCF2564.jpg"
        },
        {
          "src": "/media/projects/urban-courts/07.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20191103-DSCF6340.jpg"
        },
        {
          "src": "/media/projects/urban-courts/09.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20200220-DSCF0198.jpg"
        },
        {
          "src": "/media/projects/urban-courts/10.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20200523-DSCF1742.jpg"
        },
        {
          "src": "/media/projects/urban-courts/11.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20200617-DSCF1974.jpg"
        },
        {
          "src": "/media/projects/urban-courts/12.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "20200617-DSCF1975.jpg"
        },
        {
          "src": "/media/projects/urban-courts/15.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20190331-DSCF0406.jpg"
        },
        {
          "src": "/media/projects/urban-courts/16.jpg",
          "width": 2500,
          "height": 2000,
          "alt": "20201201-DSCF3702.jpg"
        },
        {
          "src": "/media/projects/urban-courts/19.jpg",
          "width": 2000,
          "height": 3000,
          "alt": "20210724-DSCF5036.jpg"
        },
        {
          "src": "/media/projects/urban-courts/20.jpg",
          "width": 2400,
          "height": 3000,
          "alt": "20210724-DSCF5005.jpg"
        },
        {
          "src": "/media/projects/urban-courts/21.jpg",
          "width": 2000,
          "height": 3000,
          "alt": "20220918-DSCF1571.jpg"
        },
        {
          "src": "/media/projects/urban-courts/23.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20211023-DSCF6373.jpg"
        },
        {
          "src": "/media/projects/urban-courts/24.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20211019-DSCF6302.jpg"
        },
        {
          "src": "/media/projects/urban-courts/25.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20211019-DSCF6276.jpg"
        },
        {
          "src": "/media/projects/urban-courts/27.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20211019-DSCF6298.jpg"
        },
        {
          "src": "/media/projects/urban-courts/28.jpg",
          "width": 2500,
          "height": 4444,
          "alt": "20211019-DSCF6263.jpg"
        },
        {
          "src": "/media/projects/urban-courts/29.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20211019-DSCF6300.jpg"
        },
        {
          "src": "/media/projects/urban-courts/32.jpg",
          "width": 2000,
          "height": 3000,
          "alt": "20221115-DSCF2192.jpg"
        },
        {
          "src": "/media/projects/urban-courts/33.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20221115-DSCF2189.jpg"
        },
        {
          "src": "/media/projects/urban-courts/34.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20221115-DSCF2188.jpg"
        }
      ]
    },
    {
      "slug": "desolate-sands",
      "categories": [
        "personal"
      ],
      "title": "Desolate Sands",
      "description": "A look into the empty resorts in Cuba during slow seasons.",
      "coverImage": {
        "src": "/media/projects/desolate-sands/01.jpg",
        "width": 2500,
        "height": 1406,
        "alt": "Desolate Sands"
      },
      "images": [
        {
          "src": "/media/projects/desolate-sands/01.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "The Roaming Dog"
        },
        {
          "src": "/media/projects/desolate-sands/03.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "The Empty Hotel"
        },
        {
          "src": "/media/projects/desolate-sands/10.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "Garbage Can and Tiki Umbrella"
        },
        {
          "src": "/media/projects/desolate-sands/12.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "Opposite Directions"
        },
        {
          "src": "/media/projects/desolate-sands/02.jpg",
          "width": 2500,
          "height": 2500,
          "alt": "Three Outdoor Showers (Wet)"
        },
        {
          "src": "/media/projects/desolate-sands/13.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "A Single Wave"
        },
        {
          "src": "/media/projects/desolate-sands/04.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "Highway Palm Tree"
        },
        {
          "src": "/media/projects/desolate-sands/06.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "The President Suite"
        },
        {
          "src": "/media/projects/desolate-sands/05.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "The Tumbling Donut"
        },
        {
          "src": "/media/projects/desolate-sands/07.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "Stranded Boats"
        },
        {
          "src": "/media/projects/desolate-sands/08.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "Off Duty"
        },
        {
          "src": "/media/projects/desolate-sands/09.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "Off Duty"
        },
        {
          "src": "/media/projects/desolate-sands/11.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "Eighteen Tiki Umbrellas "
        },
        {
          "src": "/media/projects/desolate-sands/14.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "The Escape"
        }
      ]
    },
    {
      "slug": "locke",
      "title": "Locke",
      "description": "The first and last rural Chinese settlement in North America, slowly getting reclaimed by nature.",
      "categories": [
        "personal"
      ],
      "coverImage": {
        "src": "/media/projects/locke/20191125-DSCF7326.jpg",
        "width": 3041,
        "height": 2028,
        "alt": "20191125-DSCF7326.jpg"
      },
      "images": [
        {
          "src": "/media/projects/locke/20191125-DSCF7264.jpg",
          "width": 3360,
          "height": 1890,
          "alt": "20191125-DSCF7264.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7282.jpg",
          "width": 3789,
          "height": 2526,
          "alt": "20191125-DSCF7282.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7275.jpg",
          "width": 4233,
          "height": 2822,
          "alt": "20191125-DSCF7275.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7273.jpg",
          "width": 3727,
          "height": 2485,
          "alt": "20191125-DSCF7273.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7271.jpg",
          "width": 4320,
          "height": 2880,
          "alt": "20191125-DSCF7271.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7270.jpg",
          "width": 3365,
          "height": 4206,
          "alt": "20191125-DSCF7270.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7279.jpg",
          "width": 3789,
          "height": 2526,
          "alt": "20191125-DSCF7279.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7320.jpg",
          "width": 2662,
          "height": 4732,
          "alt": "20191125-DSCF7320.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7318.jpg",
          "width": 2560,
          "height": 3840,
          "alt": "20191125-DSCF7318.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7317.jpg",
          "width": 2304,
          "height": 3456,
          "alt": "20191125-DSCF7317.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7269.jpg",
          "width": 4766,
          "height": 2681,
          "alt": "20191125-DSCF7269.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7276.jpg",
          "width": 3137,
          "height": 4706,
          "alt": "20191125-DSCF7276.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7328.jpg",
          "width": 3667,
          "height": 2445,
          "alt": "20191125-DSCF7328.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7326.jpg",
          "width": 3041,
          "height": 2028,
          "alt": "20191125-DSCF7326.jpg"
        },
        {
          "src": "/media/projects/locke/20191125-DSCF7323.jpg",
          "width": 2000,
          "height": 3000,
          "alt": "20191125-DSCF7323.jpg"
        }
      ]
    },
    {
      "slug": "ethereal",
      "title": "Ethereal",
      "description": "Ethereal dance movements of jellyfish",
      "categories": [
        "personal"
      ],
      "coverImage": {
        "src": "/media/projects/ethereal/20191123-DSCF7045.jpg",
        "width": 4000,
        "height": 5000,
        "alt": "20191123-DSCF7045.jpg"
      },
      "images": [
        {
          "src": "/media/projects/ethereal/20191123-DSCF7045.jpg",
          "width": 4000,
          "height": 5000,
          "alt": "20191123-DSCF7045.jpg"
        },
        {
          "src": "/media/projects/ethereal/20191123-DSCF7048.jpg",
          "width": 3223,
          "height": 4029,
          "alt": "20191123-DSCF7048.jpg"
        },
        {
          "src": "/media/projects/ethereal/20191123-DSCF7047.jpg",
          "width": 3641,
          "height": 4551,
          "alt": "20191123-DSCF7047.jpg"
        },
        {
          "src": "/media/projects/ethereal/20191123-DSCF7090.jpg",
          "width": 3802,
          "height": 5703,
          "alt": "20191123-DSCF7090.jpg"
        },
        {
          "src": "/media/projects/ethereal/20191123-DSCF7071.jpg",
          "width": 5774,
          "height": 3849,
          "alt": "20191123-DSCF7071.jpg"
        },
        {
          "src": "/media/projects/ethereal/20191123-DSCF7084.jpg",
          "width": 3657,
          "height": 5485,
          "alt": "20191123-DSCF7084.jpg"
        },
        {
          "src": "/media/projects/ethereal/20191123-DSCF7076.jpg",
          "width": 5346,
          "height": 3564,
          "alt": "20191123-DSCF7076.jpg"
        },
        {
          "src": "/media/projects/ethereal/20191123-DSCF7087.jpg",
          "width": 6000,
          "height": 4000,
          "alt": "20191123-DSCF7087.jpg"
        },
        {
          "src": "/media/projects/ethereal/20191123-DSCF7092.jpg",
          "width": 3887,
          "height": 5830,
          "alt": "20191123-DSCF7092.jpg"
        }
      ]
    },
    {
      "slug": "portraits",
      "categories": [
        "portrait",
        "personal"
      ],
      "title": "Portraits",
      "description": "A selection of portraits, in and out of studios.",
      "coverImage": {
        "src": "/media/projects/portraits/01.jpg",
        "width": 2500,
        "height": 3750,
        "alt": "Portraits"
      },
      "images": [
        {
          "src": "/media/projects/portraits/01.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20200321-DSCF0968.jpg"
        },
        {
          "src": "/media/projects/portraits/02.jpg",
          "width": 2500,
          "height": 2000,
          "alt": "20200321-DSCF0969.jpg"
        },
        {
          "src": "/media/projects/portraits/03.jpg",
          "width": 2500,
          "height": 1064,
          "alt": "20200321-DSCF0937.jpg"
        },
        {
          "src": "/media/projects/portraits/04.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "20200410-DSCF1132.jpg"
        },
        {
          "src": "/media/projects/portraits/05.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20200410-DSCF1118.jpg"
        },
        {
          "src": "/media/projects/portraits/06.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20200410-DSCF1126.jpg"
        },
        {
          "src": "/media/projects/portraits/09.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20200318-DSCF0855.jpg"
        },
        {
          "src": "/media/projects/portraits/08.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20190928-DSCF4373.jpg"
        },
        {
          "src": "/media/projects/portraits/15.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230810-DSCF4002.jpg"
        },
        {
          "src": "/media/projects/portraits/17.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230913-DSCF3388.jpg"
        },
        {
          "src": "/media/projects/portraits/14.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230808-DSCF3426.jpg"
        },
        {
          "src": "/media/projects/portraits/16.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230913-FUJIFILM X-T5 7728x5152_003418.jpg"
        },
        {
          "src": "/media/projects/portraits/10.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20200321-DSCF0989.jpg"
        },
        {
          "src": "/media/projects/portraits/11.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20200321-DSCF0982.jpg"
        },
        {
          "src": "/media/projects/portraits/13.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230809-DSCF3675.jpg"
        },
        {
          "src": "/media/projects/portraits/22.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20231002-DSCF5345.jpg"
        },
        {
          "src": "/media/projects/portraits/23.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230930-DSCF4831.jpg"
        },
        {
          "src": "/media/projects/portraits/24.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230811-DSCF4084-2.jpg"
        }
      ]
    },
    {
      "slug": "figma-2025",
      "title": "Figma 2025",
      "description": "",
      "categories": [
        "film",
        "portrait"
      ],
      "coverImage": {
        "src": "/media/projects/figma-2025/20250814-000049550031.jpg",
        "width": 2378,
        "height": 3587,
        "alt": "20250814-000049550031.jpg"
      },
      "images": [
        {
          "src": "/media/projects/figma-2025/20250814-000049550006.jpg",
          "width": 2186,
          "height": 3297,
          "alt": "20250814-000049550006.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049500019.jpg",
          "width": 2140,
          "height": 3228,
          "alt": "20250814-000049500019.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049550024.jpg",
          "width": 3587,
          "height": 2378,
          "alt": "20250814-000049550024.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250811-000044020024.jpg",
          "width": 2084,
          "height": 3144,
          "alt": "20250811-000044020024.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049510032.jpg",
          "width": 1712,
          "height": 2582,
          "alt": "20250814-000049510032.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049550002.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049550002.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250811-000044010027.jpg",
          "width": 2313,
          "height": 3489,
          "alt": "20250811-000044010027.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049530006.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049530006.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049550016.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049550016.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049530023.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049530023.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250811-000044010021.jpg",
          "width": 2274,
          "height": 3430,
          "alt": "20250811-000044010021.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049530017.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049530017.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049530019.jpg",
          "width": 2167,
          "height": 3268,
          "alt": "20250814-000049530019.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049530001.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049530001.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049550031.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049550031.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049510022.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049510022.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049510009.jpg",
          "width": 2164,
          "height": 3264,
          "alt": "20250814-000049510009.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049500036.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049500036.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250814-000049500010.jpg",
          "width": 2378,
          "height": 3587,
          "alt": "20250814-000049500010.jpg"
        },
        {
          "src": "/media/projects/figma-2025/20250811-000044020005.jpg",
          "width": 2237,
          "height": 3375,
          "alt": "20250811-000044020005.jpg"
        }
      ]
    },
    {
      "slug": "figma-2023",
      "categories": [
        "portrait"
      ],
      "title": "Figma 2023",
      "description": "",
      "coverImage": {
        "src": "/media/projects/figma-2023/01.jpg",
        "width": 2500,
        "height": 3750,
        "alt": "20230808-DSCF3302.jpg"
      },
      "images": [
        {
          "src": "/media/projects/figma-2023/01.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230808-DSCF3302.jpg"
        },
        {
          "src": "/media/projects/figma-2023/02.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230808-DSCF3419.jpg"
        },
        {
          "src": "/media/projects/figma-2023/03.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230809-DSCF3650.jpg"
        },
        {
          "src": "/media/projects/figma-2023/04.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230726-DSCF2482.jpg"
        },
        {
          "src": "/media/projects/figma-2023/05.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230726-DSCF2619.jpg"
        },
        {
          "src": "/media/projects/figma-2023/06.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230809-DSCF3637.jpg"
        },
        {
          "src": "/media/projects/figma-2023/07.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230809-DSCF3540.jpg"
        },
        {
          "src": "/media/projects/figma-2023/08.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230726-DSCF2565.jpg"
        },
        {
          "src": "/media/projects/figma-2023/09.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230726-DSCF2424.jpg"
        },
        {
          "src": "/media/projects/figma-2023/10.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20230726-DSCF2519.jpg"
        }
      ]
    },
    {
      "slug": "figma",
      "categories": [
        "portrait"
      ],
      "title": "Figma 2022",
      "description": "",
      "coverImage": {
        "src": "/media/projects/figma/01.jpg",
        "width": 2500,
        "height": 3750,
        "alt": "20220608-DSCF7438.jpg"
      },
      "images": [
        {
          "src": "/media/projects/figma/01.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220608-DSCF7438.jpg"
        },
        {
          "src": "/media/projects/figma/02.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220608-DSCF7431.jpg"
        },
        {
          "src": "/media/projects/figma/03.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20220607-DSCF6776.jpg"
        },
        {
          "src": "/media/projects/figma/04.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF7109.jpg"
        },
        {
          "src": "/media/projects/figma/05.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF6933.jpg"
        },
        {
          "src": "/media/projects/figma/06.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20220607-DSCF6879.jpg"
        },
        {
          "src": "/media/projects/figma/07.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF6903.jpg"
        },
        {
          "src": "/media/projects/figma/08.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220714-DSCF7875.jpg"
        },
        {
          "src": "/media/projects/figma/09.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF6798.jpg"
        },
        {
          "src": "/media/projects/figma/10.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF6725.jpg"
        },
        {
          "src": "/media/projects/figma/11.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF6917.jpg"
        },
        {
          "src": "/media/projects/figma/12.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF6936.jpg"
        },
        {
          "src": "/media/projects/figma/13.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF7115.jpg"
        },
        {
          "src": "/media/projects/figma/14.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20220607-DSCF7150.jpg"
        },
        {
          "src": "/media/projects/figma/15.jpg",
          "width": 2500,
          "height": 1667,
          "alt": "20220608-DSCF7458.jpg"
        }
      ]
    },
    {
      "slug": "yukimi-justin",
      "categories": [
        "film",
        "portrait"
      ],
      "title": "Yukimi & Justin",
      "description": "Engagement photos for the two lovers that met at a bus stop.",
      "coverImage": {
        "src": "/media/projects/yukimi-justin/02.jpg",
        "width": 1951,
        "height": 2943,
        "alt": "Yukimi & Justin"
      },
      "images": [
        {
          "src": "/media/projects/yukimi-justin/02.jpg",
          "width": 1951,
          "height": 2943,
          "alt": "20250708-86835_MYA_002_09.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/03.jpg",
          "width": 3275,
          "height": 2171,
          "alt": "20250708-86835_MYA_002_12.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/04.jpg",
          "width": 2046,
          "height": 3086,
          "alt": "20250708-86835_MYA_002_14.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/05.jpg",
          "width": 2171,
          "height": 3275,
          "alt": "20250708-86835_MYA_002_16.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/06.jpg",
          "width": 3275,
          "height": 2171,
          "alt": "20250708-86835_MYA_002_18.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/07.jpg",
          "width": 2171,
          "height": 3275,
          "alt": "20250708-86835_MYA_002_22.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/08.jpg",
          "width": 1979,
          "height": 2985,
          "alt": "20250708-86835_MYA_002_26.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/09.jpg",
          "width": 1899,
          "height": 2865,
          "alt": "20250708-86835_MYA_002_31.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/10.jpg",
          "width": 1992,
          "height": 3005,
          "alt": "20250708-86835_MYA_002_32.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/11.jpg",
          "width": 1967,
          "height": 2968,
          "alt": "20250708-86835_MYA_002_33.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/12.jpg",
          "width": 1992,
          "height": 3005,
          "alt": "20250708-86835_MYA_002_37.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/13.jpg",
          "width": 3275,
          "height": 2171,
          "alt": "20250708-86835_MYA_003_02.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/14.jpg",
          "width": 1974,
          "height": 2978,
          "alt": "20250708-86835_MYA_003_03.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/15.jpg",
          "width": 3165,
          "height": 2098,
          "alt": "20250708-86835_MYA_003_06.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/16.jpg",
          "width": 2097,
          "height": 3164,
          "alt": "20250708-86835_MYA_003_09.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/17.jpg",
          "width": 3008,
          "height": 1994,
          "alt": "20250708-86835_MYA_003_12.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/18.jpg",
          "width": 3161,
          "height": 2095,
          "alt": "20250708-86835_MYA_003_13.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/19.jpg",
          "width": 2063,
          "height": 3112,
          "alt": "20250708-86835_MYA_003_16.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/20.jpg",
          "width": 2859,
          "height": 1895,
          "alt": "20250708-86835_MYA_003_18.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/21.jpg",
          "width": 3007,
          "height": 1993,
          "alt": "20250708-86835_MYA_003_23.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/22.jpg",
          "width": 2076,
          "height": 3132,
          "alt": "20250708-86835_MYA_003_24.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/23.jpg",
          "width": 2171,
          "height": 3275,
          "alt": "20250708-86835_MYA_003_26.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/24.jpg",
          "width": 1800,
          "height": 2716,
          "alt": "20250708-86835_MYA_003_29.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/25.jpg",
          "width": 1924,
          "height": 2902,
          "alt": "20250708-86835_MYA_003_32.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/26.jpg",
          "width": 3038,
          "height": 2014,
          "alt": "20250708-86835_MYA_003_35.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/27.jpg",
          "width": 3177,
          "height": 2106,
          "alt": "20250708-86835_MYA_003_37.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/28.jpg",
          "width": 3275,
          "height": 2171,
          "alt": "20250708-86835_MYA_004_01.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/29.jpg",
          "width": 1933,
          "height": 2916,
          "alt": "20250708-86835_MYA_004_05.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/30.jpg",
          "width": 2171,
          "height": 3275,
          "alt": "20250708-86835_MYA_004_08.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/31.jpg",
          "width": 2748,
          "height": 1822,
          "alt": "20250708-86835_MYA_004_11.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/32.jpg",
          "width": 3171,
          "height": 2102,
          "alt": "20250708-86835_MYA_004_13.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/33.jpg",
          "width": 3275,
          "height": 2171,
          "alt": "20250708-86835_MYA_004_15.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/34.jpg",
          "width": 3275,
          "height": 2171,
          "alt": "20250708-86835_MYA_004_16.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/35.jpg",
          "width": 2941,
          "height": 1950,
          "alt": "20250708-86835_MYA_004_19.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/36.jpg",
          "width": 2976,
          "height": 1973,
          "alt": "20250708-86835_MYA_004_28.jpg"
        },
        {
          "src": "/media/projects/yukimi-justin/37.jpg",
          "width": 1873,
          "height": 2826,
          "alt": "20250708-86835_MYA_004_29.jpg"
        }
      ]
    },
    {
      "slug": "dustin",
      "categories": [
        "portrait"
      ],
      "title": "Dustin",
      "description": "",
      "coverImage": {
        "src": "/media/projects/dustin/01.jpg",
        "width": 2500,
        "height": 3750,
        "alt": "20210508-DSCF4205.jpg"
      },
      "images": [
        {
          "src": "/media/projects/dustin/01.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20210508-DSCF4205.jpg"
        },
        {
          "src": "/media/projects/dustin/02.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20210508-DSCF4188.jpg"
        },
        {
          "src": "/media/projects/dustin/04.jpg",
          "width": 2500,
          "height": 1406,
          "alt": "20210508-DSCF4154.jpg"
        },
        {
          "src": "/media/projects/dustin/05.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20210508-DSCF4138.jpg"
        },
        {
          "src": "/media/projects/dustin/06.jpg",
          "width": 2500,
          "height": 3125,
          "alt": "20210508-DSCF4106.jpg"
        },
        {
          "src": "/media/projects/dustin/07.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20210508-DSCF4327.jpg"
        },
        {
          "src": "/media/projects/dustin/08.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20210508-DSCF4264.jpg"
        },
        {
          "src": "/media/projects/dustin/09.jpg",
          "width": 2500,
          "height": 3750,
          "alt": "20210508-DSCF4257.jpg"
        }
      ]
    }
  ],
  "featuredProjectSlugs": [
    "the-bridge-reconstructed",
    "portraits",
    "desolate-sands",
    "urban-courts"
  ]
} as const;
